# Generated by Django 3.2.7 on 2022-08-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tests_passed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
