# Generated by Django 3.2.7 on 2022-08-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_tests_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tests_passed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
