# Generated by Django 3.2.7 on 2022-08-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_tests_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
            ],
            options={
                'ordering': ['-final_score'],
            },
            bases=('account.user',),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='account_use_rating__afe162_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='account_use_group_r_60ccd6_idx',
        ),
    ]
