# Generated by Django 3.2.7 on 2022-08-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('quiz', '0001_initial'),
        ('account', '0004_auto_20220803_1349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
    ]
