# Generated by Django 3.2.7 on 2022-08-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
        ),
    ]
