# Generated by Django 3.2.7 on 2022-08-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_myuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Leaderboard', 'verbose_name_plural': 'Leaderboard'},
        ),
    ]
