# Generated by Django 3.2.7 on 2022-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztakerresponse',
            name='factual_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
